package org.sytes.data.server.fengyun.dom;

import java.util.Date;

/**
 * 我的比赛记录
 * @author wang
 *
 */
public class MySportMatchLog {
    private Integer id;

    /**
     *
     *是否是我发起的比赛
     */
    private Boolean isPromoter;

    /**
     *场地id
     */
    private Integer placeId;

    /**
     *场地名
     */
    private String placeName;

    private Date startTime;

	private Date endTime;

    /**
     *比赛地址
     */
    private String sportAdress;

    /**
     *比赛状态
     */
    private Integer mathState;
    /**
     * 所在场地订单id
     */
    private int orederId;
    private long userId;
    private Date updateTime;
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_sport_match_log.id
     *
     * @return the value of my_sport_match_log.id
     *
     * @mbg.generated Sat Jun 08 08:09:12 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_sport_match_log.id
     *
     * @param id the value for my_sport_match_log.id
     *
     * @mbg.generated Sat Jun 08 08:09:12 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_sport_match_log.is_promoter
     *
     * @return the value of my_sport_match_log.is_promoter
     *
     * @mbg.generated Sat Jun 08 08:09:12 CST 2019
     */
    public Boolean getIsPromoter() {
        return isPromoter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_sport_match_log.is_promoter
     *
     * @param isPromoter the value for my_sport_match_log.is_promoter
     *
     * @mbg.generated Sat Jun 08 08:09:12 CST 2019
     */
    public void setIsPromoter(Boolean isPromoter) {
        this.isPromoter = isPromoter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_sport_match_log.place_id
     *
     * @return the value of my_sport_match_log.place_id
     *
     * @mbg.generated Sat Jun 08 08:09:12 CST 2019
     */
    public Integer getPlaceId() {
        return placeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_sport_match_log.place_id
     *
     * @param placeId the value for my_sport_match_log.place_id
     *
     * @mbg.generated Sat Jun 08 08:09:12 CST 2019
     */
    public void setPlaceId(Integer placeId) {
        this.placeId = placeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_sport_match_log.place_name
     *
     * @return the value of my_sport_match_log.place_name
     *
     * @mbg.generated Sat Jun 08 08:09:12 CST 2019
     */
    public String getPlaceName() {
        return placeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_sport_match_log.place_name
     *
     * @param placeName the value for my_sport_match_log.place_name
     *
     * @mbg.generated Sat Jun 08 08:09:12 CST 2019
     */
    public void setPlaceName(String placeName) {
        this.placeName = placeName;
    }

 

    public String getSportAdress() {
        return sportAdress;
    }

  
    public void setSportAdress(String sportAdress) {
        this.sportAdress = sportAdress;
    }

   
    public Integer getMathState() {
        return mathState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_sport_match_log.math_state
     *
     * @param mathState the value for my_sport_match_log.math_state
     *
     * @mbg.generated Sat Jun 08 08:09:12 CST 2019
     */
    public void setMathState(Integer mathState) {
        this.mathState = mathState;
    }

	public int getOrederId() {
		return orederId;
	}

	public void setOrederId(int orederId) {
		this.orederId = orederId;
	}

	public long getUserId() {
		return userId;
	}

	public void setUserId(long userId) {
		this.userId = userId;
	}

	public Date getStartTime() {
		return startTime;
	}

	public void setStartTime(Date startTime) {
		this.startTime = startTime;
	}

	public Date getEndTime() {
		return endTime;
	}

	public void setEndTime(Date endTime) {
		this.endTime = endTime;
	}

	public Date getUpdateTime() {
		return updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}
}