package org.sytes.data.server.fengyun.dom;

import java.util.concurrent.atomic.AtomicInteger;

/**
 * 用户信息
 * @author wang
 *
 */
public class UserInfo {
	private Long id;
	/**
	 * 用户名
	 */
	private String userName;
	
	private String phone;

	//省份
	private String province;
	
	private String city;
	/**
	 * 用户类型1普通2场主
	 */
	private Integer userType;
	/**
	 * 场主当前余额（分）
	 */
	private AtomicInteger gold = new AtomicInteger(0);

	
	public Long getId() {
		return id;
	}

	
	public void setId(Long id) {
		this.id = id;
	}

	public String getUserName() {
		return userName;
	}

	
	public void setUserName(String userName) {
		this.userName = userName;
	}

	
	public String getPhone() {
		return phone;
	}

	
	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getProvince() {
		return province;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_info.province
	 * @param province  the value for user_info.province
	 * @mbg.generated  Tue Jun 04 19:20:50 CST 2019
	 */
	public void setProvince(String province) {
		this.province = province;
	}

	
	public String getCity() {
		return city;
	}

	
	public void setCity(String city) {
		this.city = city;
	}

	public Integer getUserType() {
		return userType;
	}

	
	public void setUserType(Integer userType) {
		this.userType = userType;
	}


	public AtomicInteger getGold() {
		return gold;
	}


	public void setGold(AtomicInteger gold) {
		this.gold = gold;
	}

	public int gold() {
		return gold.get();
	}

}