// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common.proto

package org.sytes.message;

public final class CommMessage {
  private CommMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface CommOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 messageId = 1;
    /**
     * <code>required int32 messageId = 1;</code>
     */
    boolean hasMessageId();
    /**
     * <code>required int32 messageId = 1;</code>
     */
    int getMessageId();

    // optional bytes pbData = 2;
    /**
     * <code>optional bytes pbData = 2;</code>
     */
    boolean hasPbData();
    /**
     * <code>optional bytes pbData = 2;</code>
     */
    com.google.protobuf.ByteString getPbData();
  }
  /**
   * Protobuf type {@code common.Comm}
   */
  public static final class Comm extends
      com.google.protobuf.GeneratedMessage
      implements CommOrBuilder {
    // Use Comm.newBuilder() to construct.
    private Comm(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Comm(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Comm defaultInstance;
    public static Comm getDefaultInstance() {
      return defaultInstance;
    }

    public Comm getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Comm(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              messageId_ = input.readInt32();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              pbData_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.sytes.message.CommMessage.internal_static_common_Comm_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.sytes.message.CommMessage.internal_static_common_Comm_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.sytes.message.CommMessage.Comm.class, org.sytes.message.CommMessage.Comm.Builder.class);
    }

    public static com.google.protobuf.Parser<Comm> PARSER =
        new com.google.protobuf.AbstractParser<Comm>() {
      public Comm parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Comm(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Comm> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 messageId = 1;
    public static final int MESSAGEID_FIELD_NUMBER = 1;
    private int messageId_;
    /**
     * <code>required int32 messageId = 1;</code>
     */
    public boolean hasMessageId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 messageId = 1;</code>
     */
    public int getMessageId() {
      return messageId_;
    }

    // optional bytes pbData = 2;
    public static final int PBDATA_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString pbData_;
    /**
     * <code>optional bytes pbData = 2;</code>
     */
    public boolean hasPbData() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional bytes pbData = 2;</code>
     */
    public com.google.protobuf.ByteString getPbData() {
      return pbData_;
    }

    private void initFields() {
      messageId_ = 0;
      pbData_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasMessageId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, messageId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, pbData_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, messageId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, pbData_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static org.sytes.message.CommMessage.Comm parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.sytes.message.CommMessage.Comm parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.sytes.message.CommMessage.Comm parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.sytes.message.CommMessage.Comm parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.sytes.message.CommMessage.Comm parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.sytes.message.CommMessage.Comm parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.sytes.message.CommMessage.Comm parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.sytes.message.CommMessage.Comm parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.sytes.message.CommMessage.Comm parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.sytes.message.CommMessage.Comm parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.sytes.message.CommMessage.Comm prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code common.Comm}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.sytes.message.CommMessage.CommOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.sytes.message.CommMessage.internal_static_common_Comm_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.sytes.message.CommMessage.internal_static_common_Comm_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.sytes.message.CommMessage.Comm.class, org.sytes.message.CommMessage.Comm.Builder.class);
      }

      // Construct using org.sytes.message.CommMessage.Comm.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        messageId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        pbData_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.sytes.message.CommMessage.internal_static_common_Comm_descriptor;
      }

      public org.sytes.message.CommMessage.Comm getDefaultInstanceForType() {
        return org.sytes.message.CommMessage.Comm.getDefaultInstance();
      }

      public org.sytes.message.CommMessage.Comm build() {
        org.sytes.message.CommMessage.Comm result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.sytes.message.CommMessage.Comm buildPartial() {
        org.sytes.message.CommMessage.Comm result = new org.sytes.message.CommMessage.Comm(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.messageId_ = messageId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.pbData_ = pbData_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.sytes.message.CommMessage.Comm) {
          return mergeFrom((org.sytes.message.CommMessage.Comm)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.sytes.message.CommMessage.Comm other) {
        if (other == org.sytes.message.CommMessage.Comm.getDefaultInstance()) return this;
        if (other.hasMessageId()) {
          setMessageId(other.getMessageId());
        }
        if (other.hasPbData()) {
          setPbData(other.getPbData());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasMessageId()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.sytes.message.CommMessage.Comm parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.sytes.message.CommMessage.Comm) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 messageId = 1;
      private int messageId_ ;
      /**
       * <code>required int32 messageId = 1;</code>
       */
      public boolean hasMessageId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 messageId = 1;</code>
       */
      public int getMessageId() {
        return messageId_;
      }
      /**
       * <code>required int32 messageId = 1;</code>
       */
      public Builder setMessageId(int value) {
        bitField0_ |= 0x00000001;
        messageId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 messageId = 1;</code>
       */
      public Builder clearMessageId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        messageId_ = 0;
        onChanged();
        return this;
      }

      // optional bytes pbData = 2;
      private com.google.protobuf.ByteString pbData_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes pbData = 2;</code>
       */
      public boolean hasPbData() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional bytes pbData = 2;</code>
       */
      public com.google.protobuf.ByteString getPbData() {
        return pbData_;
      }
      /**
       * <code>optional bytes pbData = 2;</code>
       */
      public Builder setPbData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        pbData_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes pbData = 2;</code>
       */
      public Builder clearPbData() {
        bitField0_ = (bitField0_ & ~0x00000002);
        pbData_ = getDefaultInstance().getPbData();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:common.Comm)
    }

    static {
      defaultInstance = new Comm(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:common.Comm)
  }

  public interface ServerCommOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 serverMessageId = 1;
    /**
     * <code>required int32 serverMessageId = 1;</code>
     */
    boolean hasServerMessageId();
    /**
     * <code>required int32 serverMessageId = 1;</code>
     */
    int getServerMessageId();

    // optional string josnData = 2;
    /**
     * <code>optional string josnData = 2;</code>
     */
    boolean hasJosnData();
    /**
     * <code>optional string josnData = 2;</code>
     */
    java.lang.String getJosnData();
    /**
     * <code>optional string josnData = 2;</code>
     */
    com.google.protobuf.ByteString
        getJosnDataBytes();
  }
  /**
   * Protobuf type {@code common.ServerComm}
   */
  public static final class ServerComm extends
      com.google.protobuf.GeneratedMessage
      implements ServerCommOrBuilder {
    // Use ServerComm.newBuilder() to construct.
    private ServerComm(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ServerComm(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ServerComm defaultInstance;
    public static ServerComm getDefaultInstance() {
      return defaultInstance;
    }

    public ServerComm getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ServerComm(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              serverMessageId_ = input.readInt32();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              josnData_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.sytes.message.CommMessage.internal_static_common_ServerComm_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.sytes.message.CommMessage.internal_static_common_ServerComm_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.sytes.message.CommMessage.ServerComm.class, org.sytes.message.CommMessage.ServerComm.Builder.class);
    }

    public static com.google.protobuf.Parser<ServerComm> PARSER =
        new com.google.protobuf.AbstractParser<ServerComm>() {
      public ServerComm parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ServerComm(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ServerComm> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 serverMessageId = 1;
    public static final int SERVERMESSAGEID_FIELD_NUMBER = 1;
    private int serverMessageId_;
    /**
     * <code>required int32 serverMessageId = 1;</code>
     */
    public boolean hasServerMessageId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 serverMessageId = 1;</code>
     */
    public int getServerMessageId() {
      return serverMessageId_;
    }

    // optional string josnData = 2;
    public static final int JOSNDATA_FIELD_NUMBER = 2;
    private java.lang.Object josnData_;
    /**
     * <code>optional string josnData = 2;</code>
     */
    public boolean hasJosnData() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string josnData = 2;</code>
     */
    public java.lang.String getJosnData() {
      java.lang.Object ref = josnData_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          josnData_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string josnData = 2;</code>
     */
    public com.google.protobuf.ByteString
        getJosnDataBytes() {
      java.lang.Object ref = josnData_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        josnData_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      serverMessageId_ = 0;
      josnData_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasServerMessageId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, serverMessageId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getJosnDataBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, serverMessageId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getJosnDataBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static org.sytes.message.CommMessage.ServerComm parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.sytes.message.CommMessage.ServerComm parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.sytes.message.CommMessage.ServerComm parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.sytes.message.CommMessage.ServerComm parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.sytes.message.CommMessage.ServerComm parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.sytes.message.CommMessage.ServerComm parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.sytes.message.CommMessage.ServerComm parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.sytes.message.CommMessage.ServerComm parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.sytes.message.CommMessage.ServerComm parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.sytes.message.CommMessage.ServerComm parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.sytes.message.CommMessage.ServerComm prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code common.ServerComm}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.sytes.message.CommMessage.ServerCommOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.sytes.message.CommMessage.internal_static_common_ServerComm_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.sytes.message.CommMessage.internal_static_common_ServerComm_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.sytes.message.CommMessage.ServerComm.class, org.sytes.message.CommMessage.ServerComm.Builder.class);
      }

      // Construct using org.sytes.message.CommMessage.ServerComm.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        serverMessageId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        josnData_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.sytes.message.CommMessage.internal_static_common_ServerComm_descriptor;
      }

      public org.sytes.message.CommMessage.ServerComm getDefaultInstanceForType() {
        return org.sytes.message.CommMessage.ServerComm.getDefaultInstance();
      }

      public org.sytes.message.CommMessage.ServerComm build() {
        org.sytes.message.CommMessage.ServerComm result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.sytes.message.CommMessage.ServerComm buildPartial() {
        org.sytes.message.CommMessage.ServerComm result = new org.sytes.message.CommMessage.ServerComm(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.serverMessageId_ = serverMessageId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.josnData_ = josnData_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.sytes.message.CommMessage.ServerComm) {
          return mergeFrom((org.sytes.message.CommMessage.ServerComm)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.sytes.message.CommMessage.ServerComm other) {
        if (other == org.sytes.message.CommMessage.ServerComm.getDefaultInstance()) return this;
        if (other.hasServerMessageId()) {
          setServerMessageId(other.getServerMessageId());
        }
        if (other.hasJosnData()) {
          bitField0_ |= 0x00000002;
          josnData_ = other.josnData_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasServerMessageId()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.sytes.message.CommMessage.ServerComm parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.sytes.message.CommMessage.ServerComm) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 serverMessageId = 1;
      private int serverMessageId_ ;
      /**
       * <code>required int32 serverMessageId = 1;</code>
       */
      public boolean hasServerMessageId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 serverMessageId = 1;</code>
       */
      public int getServerMessageId() {
        return serverMessageId_;
      }
      /**
       * <code>required int32 serverMessageId = 1;</code>
       */
      public Builder setServerMessageId(int value) {
        bitField0_ |= 0x00000001;
        serverMessageId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 serverMessageId = 1;</code>
       */
      public Builder clearServerMessageId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        serverMessageId_ = 0;
        onChanged();
        return this;
      }

      // optional string josnData = 2;
      private java.lang.Object josnData_ = "";
      /**
       * <code>optional string josnData = 2;</code>
       */
      public boolean hasJosnData() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string josnData = 2;</code>
       */
      public java.lang.String getJosnData() {
        java.lang.Object ref = josnData_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          josnData_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string josnData = 2;</code>
       */
      public com.google.protobuf.ByteString
          getJosnDataBytes() {
        java.lang.Object ref = josnData_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          josnData_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string josnData = 2;</code>
       */
      public Builder setJosnData(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        josnData_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string josnData = 2;</code>
       */
      public Builder clearJosnData() {
        bitField0_ = (bitField0_ & ~0x00000002);
        josnData_ = getDefaultInstance().getJosnData();
        onChanged();
        return this;
      }
      /**
       * <code>optional string josnData = 2;</code>
       */
      public Builder setJosnDataBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        josnData_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:common.ServerComm)
    }

    static {
      defaultInstance = new ServerComm(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:common.ServerComm)
  }

  public interface ServerMsgOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 serverId = 1;
    /**
     * <code>required int32 serverId = 1;</code>
     */
    boolean hasServerId();
    /**
     * <code>required int32 serverId = 1;</code>
     */
    int getServerId();

    // required string serverName = 2;
    /**
     * <code>required string serverName = 2;</code>
     */
    boolean hasServerName();
    /**
     * <code>required string serverName = 2;</code>
     */
    java.lang.String getServerName();
    /**
     * <code>required string serverName = 2;</code>
     */
    com.google.protobuf.ByteString
        getServerNameBytes();

    // required int32 state = 3;
    /**
     * <code>required int32 state = 3;</code>
     *
     * <pre>
     *状态0关闭1开启
     * </pre>
     */
    boolean hasState();
    /**
     * <code>required int32 state = 3;</code>
     *
     * <pre>
     *状态0关闭1开启
     * </pre>
     */
    int getState();
  }
  /**
   * Protobuf type {@code common.ServerMsg}
   */
  public static final class ServerMsg extends
      com.google.protobuf.GeneratedMessage
      implements ServerMsgOrBuilder {
    // Use ServerMsg.newBuilder() to construct.
    private ServerMsg(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ServerMsg(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ServerMsg defaultInstance;
    public static ServerMsg getDefaultInstance() {
      return defaultInstance;
    }

    public ServerMsg getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ServerMsg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              serverId_ = input.readInt32();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              serverName_ = input.readBytes();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              state_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.sytes.message.CommMessage.internal_static_common_ServerMsg_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.sytes.message.CommMessage.internal_static_common_ServerMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.sytes.message.CommMessage.ServerMsg.class, org.sytes.message.CommMessage.ServerMsg.Builder.class);
    }

    public static com.google.protobuf.Parser<ServerMsg> PARSER =
        new com.google.protobuf.AbstractParser<ServerMsg>() {
      public ServerMsg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ServerMsg(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ServerMsg> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 serverId = 1;
    public static final int SERVERID_FIELD_NUMBER = 1;
    private int serverId_;
    /**
     * <code>required int32 serverId = 1;</code>
     */
    public boolean hasServerId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 serverId = 1;</code>
     */
    public int getServerId() {
      return serverId_;
    }

    // required string serverName = 2;
    public static final int SERVERNAME_FIELD_NUMBER = 2;
    private java.lang.Object serverName_;
    /**
     * <code>required string serverName = 2;</code>
     */
    public boolean hasServerName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string serverName = 2;</code>
     */
    public java.lang.String getServerName() {
      java.lang.Object ref = serverName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          serverName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string serverName = 2;</code>
     */
    public com.google.protobuf.ByteString
        getServerNameBytes() {
      java.lang.Object ref = serverName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        serverName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required int32 state = 3;
    public static final int STATE_FIELD_NUMBER = 3;
    private int state_;
    /**
     * <code>required int32 state = 3;</code>
     *
     * <pre>
     *状态0关闭1开启
     * </pre>
     */
    public boolean hasState() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int32 state = 3;</code>
     *
     * <pre>
     *状态0关闭1开启
     * </pre>
     */
    public int getState() {
      return state_;
    }

    private void initFields() {
      serverId_ = 0;
      serverName_ = "";
      state_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasServerId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasServerName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasState()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, serverId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getServerNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, state_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, serverId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getServerNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, state_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static org.sytes.message.CommMessage.ServerMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.sytes.message.CommMessage.ServerMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.sytes.message.CommMessage.ServerMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.sytes.message.CommMessage.ServerMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.sytes.message.CommMessage.ServerMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.sytes.message.CommMessage.ServerMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.sytes.message.CommMessage.ServerMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.sytes.message.CommMessage.ServerMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.sytes.message.CommMessage.ServerMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.sytes.message.CommMessage.ServerMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.sytes.message.CommMessage.ServerMsg prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code common.ServerMsg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.sytes.message.CommMessage.ServerMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.sytes.message.CommMessage.internal_static_common_ServerMsg_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.sytes.message.CommMessage.internal_static_common_ServerMsg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.sytes.message.CommMessage.ServerMsg.class, org.sytes.message.CommMessage.ServerMsg.Builder.class);
      }

      // Construct using org.sytes.message.CommMessage.ServerMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        serverId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        serverName_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        state_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.sytes.message.CommMessage.internal_static_common_ServerMsg_descriptor;
      }

      public org.sytes.message.CommMessage.ServerMsg getDefaultInstanceForType() {
        return org.sytes.message.CommMessage.ServerMsg.getDefaultInstance();
      }

      public org.sytes.message.CommMessage.ServerMsg build() {
        org.sytes.message.CommMessage.ServerMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.sytes.message.CommMessage.ServerMsg buildPartial() {
        org.sytes.message.CommMessage.ServerMsg result = new org.sytes.message.CommMessage.ServerMsg(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.serverId_ = serverId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.serverName_ = serverName_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.state_ = state_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.sytes.message.CommMessage.ServerMsg) {
          return mergeFrom((org.sytes.message.CommMessage.ServerMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.sytes.message.CommMessage.ServerMsg other) {
        if (other == org.sytes.message.CommMessage.ServerMsg.getDefaultInstance()) return this;
        if (other.hasServerId()) {
          setServerId(other.getServerId());
        }
        if (other.hasServerName()) {
          bitField0_ |= 0x00000002;
          serverName_ = other.serverName_;
          onChanged();
        }
        if (other.hasState()) {
          setState(other.getState());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasServerId()) {
          
          return false;
        }
        if (!hasServerName()) {
          
          return false;
        }
        if (!hasState()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.sytes.message.CommMessage.ServerMsg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.sytes.message.CommMessage.ServerMsg) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 serverId = 1;
      private int serverId_ ;
      /**
       * <code>required int32 serverId = 1;</code>
       */
      public boolean hasServerId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 serverId = 1;</code>
       */
      public int getServerId() {
        return serverId_;
      }
      /**
       * <code>required int32 serverId = 1;</code>
       */
      public Builder setServerId(int value) {
        bitField0_ |= 0x00000001;
        serverId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 serverId = 1;</code>
       */
      public Builder clearServerId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        serverId_ = 0;
        onChanged();
        return this;
      }

      // required string serverName = 2;
      private java.lang.Object serverName_ = "";
      /**
       * <code>required string serverName = 2;</code>
       */
      public boolean hasServerName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string serverName = 2;</code>
       */
      public java.lang.String getServerName() {
        java.lang.Object ref = serverName_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          serverName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string serverName = 2;</code>
       */
      public com.google.protobuf.ByteString
          getServerNameBytes() {
        java.lang.Object ref = serverName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          serverName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string serverName = 2;</code>
       */
      public Builder setServerName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        serverName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string serverName = 2;</code>
       */
      public Builder clearServerName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        serverName_ = getDefaultInstance().getServerName();
        onChanged();
        return this;
      }
      /**
       * <code>required string serverName = 2;</code>
       */
      public Builder setServerNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        serverName_ = value;
        onChanged();
        return this;
      }

      // required int32 state = 3;
      private int state_ ;
      /**
       * <code>required int32 state = 3;</code>
       *
       * <pre>
       *状态0关闭1开启
       * </pre>
       */
      public boolean hasState() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int32 state = 3;</code>
       *
       * <pre>
       *状态0关闭1开启
       * </pre>
       */
      public int getState() {
        return state_;
      }
      /**
       * <code>required int32 state = 3;</code>
       *
       * <pre>
       *状态0关闭1开启
       * </pre>
       */
      public Builder setState(int value) {
        bitField0_ |= 0x00000004;
        state_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 state = 3;</code>
       *
       * <pre>
       *状态0关闭1开启
       * </pre>
       */
      public Builder clearState() {
        bitField0_ = (bitField0_ & ~0x00000004);
        state_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:common.ServerMsg)
    }

    static {
      defaultInstance = new ServerMsg(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:common.ServerMsg)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_common_Comm_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_common_Comm_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_common_ServerComm_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_common_ServerComm_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_common_ServerMsg_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_common_ServerMsg_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014common.proto\022\006common\")\n\004Comm\022\021\n\tmessag" +
      "eId\030\001 \002(\005\022\016\n\006pbData\030\002 \001(\014\"7\n\nServerComm\022" +
      "\027\n\017serverMessageId\030\001 \002(\005\022\020\n\010josnData\030\002 \001" +
      "(\t\"@\n\tServerMsg\022\020\n\010serverId\030\001 \002(\005\022\022\n\nser" +
      "verName\030\002 \002(\t\022\r\n\005state\030\003 \002(\005B \n\021org.syte" +
      "s.messageB\013CommMessage"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_common_Comm_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_common_Comm_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_common_Comm_descriptor,
              new java.lang.String[] { "MessageId", "PbData", });
          internal_static_common_ServerComm_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_common_ServerComm_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_common_ServerComm_descriptor,
              new java.lang.String[] { "ServerMessageId", "JosnData", });
          internal_static_common_ServerMsg_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_common_ServerMsg_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_common_ServerMsg_descriptor,
              new java.lang.String[] { "ServerId", "ServerName", "State", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
